### ISSUE TITLE
G.6.  Clarify where the protocol stands with respect to submission and TLS issues

### ISSUE THREAD

**Issue by aamelnikov** [ietf-wg-emailcore/emailcore#80]
1.  submission on port 587
   2.  submission on port 465
   3.  TLS relay on a port different from 25 (whenever)
   4.  Recommendations about general use of transport layer (hop by hop)
       security, particularly encryption including consideration of RFC
       8314.

The MTA-to-MTA relay case is now covered by now closed ticket #54. Do we need to say anything about submission and RFC 8314?

**Comment by toddherr** [comment]
Per November 2023 interim, acknowledge existence of port 465 in A/S and close the ticket

Update text in 6.4 from this:

SMTP AUTH defines a method for a client to identify itself to a Message Submission Agent (MSA) when presenting a message for transmission, usually using port 587 rather than the traditional port 25. 

To this:

SMTP AUTH defines a method for a client to identify itself to a Message Submission Agent (MSA) when presenting a message for transmission, usually using ports 465 or 587 rather than the traditional port 25.

**Comment by toddherr** [comment]
A/S author was requested to publish a new rev on 13 December 2023 with text from previous comment mentioning port 465 included. Will close issue once new rev is published.

**Comment by toddherr** [comment]
New rev was published on 18 December 2023. Closing ticket.
